import React, { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useDashboard } from '../context/DashboardContext.jsx';
import { usePersistentState } from '../hooks/usePersistentState.js';
import { getVerticalOrder, getPhaseOrder } from '../config/instance-config.js';

// ---------------------------------------------------------------------------
// Data views — render the derived data layer (__Operations/Dashboard/data/*.json,
// served at /api/data/, regenerated by `mot-tools.js extract`). Markdown stays
// the source of truth; these views are read-only projections of it.
// ---------------------------------------------------------------------------

const dataCache = new Map();

// GRACEFUL-EMPTY sentinel (see DATA_CONTRACT.md): a 404 means the data JSON is
// simply absent — the instance hasn't run the extractor that produces this tab's
// feed (or, for a plugin tab, hasn't supplied one). That is a configuration state,
// NOT an error, so views render an explicit empty state rather than a red error or
// a blank screen. Any OTHER failure (500, network, parse) is surfaced as an error.
const NOT_CONFIGURED = Symbol('not-configured');

function useData(name) {
  const [state, setState] = useState(() => dataCache.get(name) || null);
  const [error, setError] = useState(null);
  const fetchInto = useCallback(() => {
    fetch(`/api/data/${name}.json`)
      .then(r => {
        if (r.ok) return r.json();
        if (r.status === 404) return Promise.reject(NOT_CONFIGURED);
        return Promise.reject(new Error(`${name}.json request failed (HTTP ${r.status})`));
      })
      .then(d => { dataCache.set(name, d); setState(d); setError(null); })
      .catch(e => setError(e === NOT_CONFIGURED ? NOT_CONFIGURED : (e.message || String(e))));
  }, [name]);
  useEffect(() => {
    if (dataCache.has(name)) { setState(dataCache.get(name)); return; }
    fetchInto();
  }, [name, fetchInto]);
  // Force a re-fetch past the module cache (the click-to-refresh stamp, after re-extract).
  const reload = useCallback(() => { dataCache.delete(name); fetchInto(); }, [name, fetchInto]);
  return [state, error, reload];
}

// Shared graceful-empty panel for a tab whose data JSON is absent (404). Explicit,
// never a crash or blank screen (DASHBOARD DATA CONTRACT requirement).
function EmptyState({ view }) {
  return (
    <div className="dv-empty">
      No data source configured for this view{view ? ` (${view})` : ''} — see DATA_CONTRACT.md
    </div>
  );
}

// True when the useData error is the not-configured sentinel (a 404).
const isNotConfigured = err => err === NOT_CONFIGURED;

function daysSince(iso) {
  if (!iso) return null;
  return Math.floor((Date.now() - new Date(iso + 'T00:00:00').getTime()) / 86400000);
}

function FreshnessDot({ iso }) {
  const d = daysSince(iso);
  const color = d == null ? 'var(--text-muted)' : d <= 14 ? '#22c55e' : d <= 30 ? '#f59e0b' : '#ef4444';
  const title = d == null ? 'no date' : `${d} day${d === 1 ? '' : 's'} ago`;
  return <span className="dv-dot" style={{ background: color }} title={title} />;
}

function GeneratedStamp({ data, onReload }) {
  if (!data?.generated_at) return null;
  return (
    <span
      className={`dv-stamp ${onReload ? 'dv-stamp--click' : ''}`}
      onClick={onReload}
      title={onReload ? 'Re-fetch the data layer (run `npm run extract` first)' : undefined}
    >
      data from {new Date(data.generated_at).toLocaleString()}{onReload ? ' — click to refresh' : ' — regenerate with npm run extract'}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Projects — status-card grid from Overview TL;DR blocks
// ---------------------------------------------------------------------------

// Canonical orders for the vertical / phase facets, + a name normaliser used to
// map Sync partners back to a project tier (Sync "importance" sort). These are
// instance-configurable: the arrays come from the manifest vocab via
// src/config/instance-config.js (getVerticalOrder / getPhaseOrder), read at call
// time so a runtime applyInstanceConfig() (from /api/config) takes effect. The
// getters return the reference orders as a fallback before any manifest is wired.
const PROJ_VERT_ORDER = getVerticalOrder();
const PROJ_PHASE_ORDER = getPhaseOrder();
const normName = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

// ── Homogenized project card helpers ────────────────────────────────────────
function truncate(s, n) { s = String(s || ''); return s.length > n ? s.slice(0, n - 1).trimEnd() + '…' : s; }

// A subproject has no tier of its own — it shows an inherited "↳ customer · Tn"
// chip — so the tier filter + facet counts must use the inherited tier too, or
// "Tier 1" would hide a sub whose chip says T1.
function effectiveTier(p) {
  return p.tier != null ? p.tier : (p.parent_id ? (p.customer_tier ?? null) : null);
}

// Deterministic monogram (initials + hashed hue) — the universal fallback when a
// project has no logo file, so a card never shows a broken image.
function monogramInitials(name) {
  const w = String(name || '').replace(/^\d{6,8}\s+/, '').split(/[\s\-/_.]+/).filter(Boolean);
  if (!w.length) return '?';
  return (w.length === 1 ? w[0].slice(0, 2) : w[0][0] + w[1][0]).toUpperCase();
}
function monogramColor(seed) {
  const s = String(seed || ''); let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return `hsl(${h % 360} 42% 30%)`;
}

// Company logo: /logos/<slug>.svg → .png → monogram. The monogram is the
// default-rendered state on any miss, so a 404 is invisible.
function Logo({ slug, name, size = 26 }) {
  const [stage, setStage] = useState(slug ? 'svg' : 'mono');
  useEffect(() => { setStage(slug ? 'svg' : 'mono'); }, [slug]);
  if (stage === 'mono') {
    return (
      <span className="dv-logo dv-logo--mono" title={name}
        style={{ width: size, height: size, background: monogramColor(slug || name) }}>
        {monogramInitials(name)}
      </span>
    );
  }
  return (
    <img className="dv-logo" alt="" title={name} width={size} height={size}
      src={`/logos/${slug}.${stage}`}
      onError={() => setStage(stage === 'svg' ? 'png' : 'mono')} />
  );
}

// One project card — five homogenized slots (logo · scope · current state ·
// last engagement · blocker) + a hover popover. Subprojects show an inherited
// "↳ customer · Tn" chip instead of their own tier and a customer link.
function ProjectCard({ p, onOpen, onOpenCustomer }) {
  const isSub = !!p.parent_id;
  const dotIso = p.card_date_is_mtime ? null : p.card_date_iso;   // neutral dot when mtime-derived
  return (
    <div className="dv-card dv-card--proj" onClick={() => onOpen(p.id)} title={`Open ${p.name} timeline`}>
      <div className="dv-card-head">
        <Logo slug={p.logo_slug} name={p.customer_name || p.name} />
        <span className="dv-card-name">{p.name}</span>
        {isSub
          ? (p.customer_name && <span className="dv-badge dv-badge--inherit" title={`Build for ${p.customer_name}`}>↳ {p.customer_name}{p.customer_tier ? ` · T${p.customer_tier}` : ''}</span>)
          : (p.tier && <span className="dv-badge dv-badge--tier">T{p.tier}</span>)}
        {p.vertical && <span className="dv-badge dv-badge--vert">{p.vertical}</span>}
        {p.phase && <span className={`dv-badge dv-badge--phase dv-badge--phase-${p.phase}`}>{p.phase}</span>}
      </div>
      {p.description && <div className="dv-card-scope">{truncate(p.description, 140)}</div>}
      {p.card_status && <div className="dv-card-status">{p.card_status}</div>}
      {p.tldr?.open_blockers && (
        <div className="dv-card-line dv-card-line--blockers"><span className="dv-key">Blocker:</span> {p.tldr.open_blockers}</div>
      )}
      <div className="dv-card-foot">
        <FreshnessDot iso={dotIso} />
        {p.card_date_iso ? (p.card_date_is_mtime ? `file modified ${p.card_date_iso}` : `last activity ${p.card_date_iso}`) : 'no date'}
        {isSub && p.customer_id && (
          <button className="dv-cust-chip" title={`Open ${p.customer_name}`}
            onClick={e => { e.stopPropagation(); onOpenCustomer(p.customer_id); }}>↳ {p.customer_name}</button>
        )}
      </div>
    </div>
  );
}

// A collapsible subgroup of nested project cards under a parent card. Two
// flavours share it: product-family "builds" (collapsed by default) and
// customer-cross-listed "customer builds" (expanded by default — a build's
// primary home in the default grid is its customer). A live filter forces it
// open so matches stay visible; the accent rail marks the customer axis.
function SubGroup({ storageKey, count, label, defaultOpen, forceOpen, accent, children }) {
  const [userOpen, setUserOpen] = usePersistentState(storageKey, defaultOpen);
  const open = forceOpen || userOpen;
  return (
    <>
      <button className={`dv-subtoggle ${open ? 'dv-subtoggle--open' : ''}`}
        onClick={() => setUserOpen(o => !o)} aria-expanded={open}>
        <span className="dv-subtoggle-caret">{open ? '▾' : '▸'}</span>
        {open ? 'Hide' : 'Show'} {count} {label}
      </button>
      {open && (
        <div className="dv-subgrid" style={accent ? { borderLeftColor: accent } : undefined}>
          {children}
        </div>
      )}
    </>
  );
}

// ── Own-attribute filtering + cross-listing (Phase 2 §2.4) ───────────────────
// A tile matches a tier/vertical/phase/search filter ONLY on its own attributes.
// Builds reach a non-matching vertical through the customer cross-listing axis,
// never by bubbling up to their product-family parent (so filtering Foundry no
// longer surfaces the Equipment wafer-level parent).
function selfMatch(p, f) {
  if (!p) return false;
  // Treat a null effective tier as the 0 ("No tier") bucket so it matches the
  // facet's effectiveTier(p)??0 — keeps a future no-tier top-level tile reachable.
  if (f.tier != null && (effectiveTier(p) ?? 0) !== f.tier) return false;
  if (f.vert != null && (p.vertical || '') !== f.vert) return false;
  if (f.phase != null && (p.phase || '') !== f.phase) return false;
  if (f.q && !(
    p.name.toLowerCase().includes(f.q) ||
    (p.description || '').toLowerCase().includes(f.q) ||
    (p.card_status || '').toLowerCase().includes(f.q))) return false;
  return true;
}
const hasFilter = f => f.tier != null || f.vert != null || f.phase != null || !!f.q;

export function ProjectsView() {
  const { openTimeline } = useDashboard();
  const [data, error, reload] = useData('projects');
  const [tierFilter, setTierFilter] = useState(null);
  const [vertFilter, setVertFilter] = useState(null);   // product vertical: Equipment/Foundry/Products/AI
  const [phaseFilter, setPhaseFilter] = useState(null); // engagement phase: engaged/acquisition/dormant/...
  const [sort, setSort] = usePersistentState('projects-sort', 'importance'); // importance|newest|name|phase
  const [q, setQ] = useState('');

  // Index + top-level split. Top-level tiles = nodes with no containment parent
  // (product-parents + leaves + customers); subprojects render only nested, but
  // every node stays in the index for cross-listing lookups.
  const { byId, topLevels } = useMemo(() => {
    const list = data?.projects || [];
    return { byId: new Map(list.map(p => [p.id, p])), topLevels: list.filter(p => !p.parent_id) };
  }, [data]);

  if (isNotConfigured(error)) return <EmptyState view="Projects" />;
  if (error) return <div className="dv-error">{error}</div>;
  if (!data) return <div className="dv-loading">Loading projects…</div>;

  const filter = { tier: tierFilter, vert: vertFilter, phase: phaseFilter, q: q.trim().toLowerCase() || null };
  const anyFilter = hasFilter(filter);
  const lookup = id => byId.get(id);

  // A node's two child axes, each narrowed to own-attribute matches when a filter
  // is active: containment = product-family subprojects (subproject_ids);
  // customer = builds that name this node as their customer (customer_build_ids).
  const resolveChildren = (p, f) => {
    const cc = (p.subproject_ids || []).map(lookup).filter(Boolean);
    const cb = (p.customer_build_ids || []).map(lookup).filter(Boolean);
    if (!hasFilter(f)) return { containment: cc, customer: cb };
    return { containment: cc.filter(c => selfMatch(c, f)), customer: cb.filter(c => selfMatch(c, f)) };
  };

  // Visible at top level if the tile matches on its own attributes, OR a
  // non-customer-build subproject matches (a vertical-split company like Edmund —
  // such a child has no other home, so its parent surfaces), OR a customer build
  // matches (cross-listing surfaces the customer tile with its matching build). A
  // matching customer build does NOT bubble its product-family parent up. (The
  // bubble is direct-child only — a deeper vertical-split grandchild whose
  // vertical no ancestor shares isn't surfaced; not a case in the 3-level data.)
  const isVisibleTop = (p, f) => {
    if (selfMatch(p, f)) return true;
    if (!hasFilter(f)) return true;
    const { containment, customer } = resolveChildren(p, f);
    return containment.some(c => !c.customer_id) || customer.length > 0;
  };

  // Recursive node render: a leaf card unless it has shown children, in which
  // case card + collapsible subgroups. Containment builds collapse by default;
  // customer builds expand by default. Depth capped at 3 levels.
  const renderNode = (p, depth, keyPrefix) => {
    const { containment, customer } = resolveChildren(p, filter);
    const showContainment = depth < 3 && containment.length > 0;
    const showCustomer = depth < 3 && customer.length > 0;
    const card = <ProjectCard p={p} onOpen={openTimeline} onOpenCustomer={openTimeline} />;
    if (!showContainment && !showCustomer) return <React.Fragment key={keyPrefix + p.id}>{card}</React.Fragment>;
    return (
      <div className="dv-parent-group" key={keyPrefix + p.id}>
        {card}
        {showContainment && (
          <SubGroup storageKey={`proj-build-open:${p.id}`} count={containment.length}
            label={`build${containment.length === 1 ? '' : 's'}`} defaultOpen={false} forceOpen={anyFilter}>
            {containment.map(c => renderNode(c, depth + 1, `${keyPrefix}${p.id}>`))}
          </SubGroup>
        )}
        {showCustomer && (
          <SubGroup storageKey={`proj-cust-open:${p.id}`} count={customer.length}
            label={`customer build${customer.length === 1 ? '' : 's'}`} defaultOpen forceOpen={anyFilter} accent="#c084fc">
            {customer.map(c => renderNode(c, depth + 1, `${keyPrefix}${p.id}@`))}
          </SubGroup>
        )}
      </div>
    );
  };

  // Visible top-level tiles under the active filter, sorted.
  const byName = (a, b) => a.name.localeCompare(b.name);
  let tops = topLevels.filter(p => isVisibleTop(p, filter));
  if (sort === 'newest') tops = [...tops].sort((a, b) => (b.card_date_iso || '').localeCompare(a.card_date_iso || '') || byName(a, b));
  else if (sort === 'name') tops = [...tops].sort(byName);
  else if (sort === 'phase') tops = [...tops].sort((a, b) => (PROJ_PHASE_ORDER.indexOf(a.phase) + 1 || 99) - (PROJ_PHASE_ORDER.indexOf(b.phase) + 1 || 99) || byName(a, b));
  else tops = [...tops].sort((a, b) => (a.tier || 9) - (b.tier || 9) || byName(a, b));

  // Facet counts == the number of top-level tiles a single-field filter reveals
  // (own-attribute visibility incl. cross-listing), so each count equals what
  // clicking it shows. Options with a zero count are dropped (no dead filters).
  const countFor = partial => topLevels.filter(p => isVisibleTop(p, { tier: null, vert: null, phase: null, q: null, ...partial })).length;
  const tiers = [...new Set(data.projects.map(p => effectiveTier(p) ?? 0))].sort((a, b) => a - b).filter(t => countFor({ tier: t }) > 0);
  const verticals = [...new Set(data.projects.map(p => p.vertical).filter(Boolean))]
    .sort((a, b) => (PROJ_VERT_ORDER.indexOf(a) + 1 || 99) - (PROJ_VERT_ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b))
    .filter(v => countFor({ vert: v }) > 0);
  const phases = [...new Set(data.projects.map(p => p.phase).filter(Boolean))]
    .sort((a, b) => (PROJ_PHASE_ORDER.indexOf(a) + 1 || 99) - (PROJ_PHASE_ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b))
    .filter(ph => countFor({ phase: ph }) > 0);

  return (
    <div className="dv-root">
      <div className="dv-toolbar">
        <input className="dv-search" placeholder="Filter projects…" value={q} onChange={e => setQ(e.target.value)} />
        <label className="dv-field">Sort
          <select className="dv-select" value={sort} onChange={e => setSort(e.target.value)}>
            <option value="importance">Importance (tier)</option>
            <option value="newest">Newest activity</option>
            <option value="name">Name (A–Z)</option>
            <option value="phase">Phase</option>
          </select>
        </label>
        <select className="dv-select" title="Filter by tier" value={tierFilter ?? ''}
          onChange={e => setTierFilter(e.target.value === '' ? null : Number(e.target.value))}>
          <option value="">All tiers ({topLevels.length})</option>
          {tiers.map(t => (
            <option key={t} value={t}>{t === 0 ? 'No tier' : `Tier ${t}`} ({countFor({ tier: t })})</option>
          ))}
        </select>
        {verticals.length > 0 && (
          <select className="dv-select" title="Filter by product vertical" value={vertFilter ?? ''}
            onChange={e => setVertFilter(e.target.value || null)}>
            <option value="">All verticals</option>
            {verticals.map(v => <option key={v} value={v}>{v} ({countFor({ vert: v })})</option>)}
          </select>
        )}
        {phases.length > 0 && (
          <select className="dv-select" title="Filter by engagement phase" value={phaseFilter ?? ''}
            onChange={e => setPhaseFilter(e.target.value || null)}>
            <option value="">All phases</option>
            {phases.map(ph => <option key={ph} value={ph}>{ph} ({countFor({ phase: ph })})</option>)}
          </select>
        )}
        <GeneratedStamp data={data} onReload={reload} />
      </div>

      <div className="dv-cardgrid">
        {tops.map(p => renderNode(p, 1, ''))}
        {tops.length === 0 && <div className="dv-empty">No projects match.</div>}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Contacts — the centralized sales/BD address book (__Sales/Contacts/Contacts.md
// → data/contacts.json). The markdown register stores PERSON fields only;
// company axes (company_role / company_vertical / company_phase / company_tier)
// are DERIVED at extract time from the linked company's Overview.md frontmatter,
// and `status` is COMPUTED from Last contact — edit the company's Overview.md
// (not the contact) to change the derived chips.
// ---------------------------------------------------------------------------
const CONTACT_VERT_ORDER = ['Equipment', 'Foundry', 'Products', 'AI'];
const cstatusSlug = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'none';

// Stable per-draft identity for client-side read-state (usePersistentState).
// Keyed on the contact email (lowercased) + the draft's generated date so a
// REGENERATED draft (new generated) becomes unread again. Falls back to the
// draft file path when generated is missing; returns null when there is no
// email or no draft (those can't be tracked and are treated as read).
function draftKey(contact) {
  const d = contact && contact.draft;
  if (!d) return null;
  const email = (contact.email || '').trim().toLowerCase();
  if (!email) return null;
  return `${email}|${d.generated || d.file || ''}`;
}

// Read-state is only meaningful when localStorage can persist it. If it's unavailable
// (private mode / disabled), degrade gracefully: every draft shows as read (no highlight,
// no count) rather than everything lighting up as unread on each visit.
const DRAFT_STATE_OK = (() => {
  try { const k = '__dv_probe__'; localStorage.setItem(k, '1'); localStorage.removeItem(k); return true; }
  catch { return false; }
})();

// Modal showing a contact's generated outreach draft (from __Sales/Contacts/drafts/),
// with a one-click copy of the full To/Subject/Body block for pasting into Outlook.
// `unread` reflects client read-state; Copy marks it read (the definitive "I took it"
// action — merely opening does not), and a small toggle lets the user flip it manually.
function DraftModal({ contact, unread, onMarkRead, onToggleRead, onClose }) {
  const d = contact.draft;
  const { selectFile } = useDashboard();
  const [copied, setCopied] = useState(false);
  if (!d) return null;
  const full = `To: ${d.to}\nSubject: ${d.subject}\n\n${d.body}`;
  const copy = () => {
    navigator.clipboard?.writeText(full).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1500); });
    onMarkRead && onMarkRead();
  };
  // Sender-reference material from the draft's optional related_material
  // frontmatter (grounds the hook / follow-up artifacts — never attached to a
  // first touch). Path items open in the right-hand file viewer (selectFile).
  const related = Array.isArray(d.related_material) ? d.related_material : [];
  const openRelated = (p) => { selectFile(p); onClose && onClose(); };
  const body = <pre className="dv-modal-body">{d.body}</pre>;
  return (
    <div className="dv-modal-backdrop" onClick={onClose}>
      <div className={`dv-modal${related.length ? ' dv-modal--wide' : ''}`} onClick={e => e.stopPropagation()}>
        <div className="dv-modal-head">
          <span>Outreach draft — {contact.name}{contact.company ? ` · ${contact.company}` : ''}</span>
          <button className="dv-modal-x" onClick={onClose} title="Close (Esc)">✕</button>
        </div>
        <div className="dv-modal-meta"><span className="dv-key">To</span> {d.to}
          {d.touch_type && <span className="dv-badge dv-badge--seg" style={{ marginLeft: 8 }}>{d.touch_type}</span>}</div>
        <div className="dv-modal-meta"><span className="dv-key">Subject</span> {d.subject}</div>
        {related.length ? (
          <div className="dv-modal-cols">
            {body}
            <aside className="dv-related">
              <div className="dv-related-head">Related material</div>
              <div className="dv-related-cap">sender reference — not for first-touch attachment</div>
              {related.map((it, i) => (
                <div key={i} className="dv-related-item">
                  {it.path ? (
                    <>
                      <button className="dv-related-file" title={it.path} onClick={() => openRelated(it.path)}>
                        {it.path.split('/').pop()}
                      </button>
                      <div className="dv-related-path">{it.path}</div>
                      {it.note && <div className="dv-related-note">{it.note}</div>}
                    </>
                  ) : (
                    <div className="dv-related-note">
                      <span className="dv-key">Suggestion</span> {(it.note || '').replace(/^suggestion:\s*/i, '')}
                    </div>
                  )}
                </div>
              ))}
            </aside>
          </div>
        ) : body}
        <div className="dv-modal-foot">
          {d.file && <span className="dv-cmuted" title={d.file}>{d.generated ? `drafted ${d.generated}` : d.file}</span>}
          <div className="dv-modal-foot-actions">
            {onToggleRead && (
              <button className="dv-toggle-read-btn" onClick={onToggleRead}
                title={unread ? 'Mark this draft as read (clears the highlight)' : 'Mark this draft as unread (re-highlight for later)'}>
                {unread ? 'Mark as read' : 'Mark as unread'}
              </button>
            )}
            <button className="dv-copy-btn" onClick={copy}>{copied ? '✓ Copied' : 'Copy email'}</button>
          </div>
        </div>
      </div>
    </div>
  );
}

// Contact avatar: custom photo (/api/contact-photo?email) → company logo (Logo) →
// monogram. `version` cache-busts after upload/reset; a 404 on the photo falls
// straight through to the company logo, so the default is always the company logo.
function ContactAvatar({ c, size = 84, version = 0 }) {
  const [photoOk, setPhotoOk] = useState(true);
  useEffect(() => { setPhotoOk(true); }, [c.email, version]);
  const src = c.email ? `/api/contact-photo?email=${encodeURIComponent(c.email)}&v=${version}` : null;
  return (
    <div className="dv-avatar-frame" style={{ width: size, height: size }}>
      {src && photoOk
        ? <img className="dv-avatar-img" src={src} alt="" draggable={false} onError={() => setPhotoOk(false)} />
        : <Logo slug={c.logo_slug} name={c.company || c.name} size={size} />}
    </div>
  );
}

// Square crop+zoom picker: pan-drag + zoom the dropped image inside a fixed frame;
// Save renders the visible square to a 256×256 JPEG (client-side canvas, no deps).
function PhotoCropper({ src, onCancel, onSave, busy }) {
  const D = 264, OUT = 256;
  const imgRef = useRef(null), drag = useRef(null);
  const [nat, setNat] = useState(null);
  const [scale, setScale] = useState(1);
  const [off, setOff] = useState({ x: 0, y: 0 });
  const bs = nat ? D / Math.min(nat.w, nat.h) : 1;            // cover baseline (shorter side fills frame)
  const dispW = nat ? nat.w * bs * scale : D, dispH = nat ? nat.h * bs * scale : D;
  const clamp = o => ({ x: Math.min(0, Math.max(D - dispW, o.x)), y: Math.min(0, Math.max(D - dispH, o.y)) });
  useEffect(() => { setOff(o => clamp(o)); /* eslint-disable-next-line */ }, [scale, nat]);
  const onLoad = e => { setNat({ w: e.target.naturalWidth, h: e.target.naturalHeight }); setScale(1); setOff({ x: 0, y: 0 }); };
  const down = e => { drag.current = { sx: e.clientX, sy: e.clientY, ox: off.x, oy: off.y }; };
  const move = e => { if (drag.current) setOff(clamp({ x: drag.current.ox + (e.clientX - drag.current.sx), y: drag.current.oy + (e.clientY - drag.current.sy) })); };
  const up = () => { drag.current = null; };
  const save = () => {
    const cv = document.createElement('canvas'); cv.width = OUT; cv.height = OUT;
    const side = D / (bs * scale), sx = (-off.x) / (bs * scale), sy = (-off.y) / (bs * scale);
    cv.getContext('2d').drawImage(imgRef.current, sx, sy, side, side, 0, 0, OUT, OUT);
    onSave(cv.toDataURL('image/jpeg', 0.9));
  };
  return (
    <div className="dv-modal-backdrop" onClick={onCancel}>
      <div className="dv-modal dv-crop-modal" onClick={e => e.stopPropagation()}>
        <div className="dv-modal-head"><span>Position &amp; crop photo</span><button className="dv-modal-x" onClick={onCancel} title="Cancel">✕</button></div>
        <div className="dv-crop-stage" style={{ width: D, height: D }} onMouseDown={down} onMouseMove={move} onMouseUp={up} onMouseLeave={up}>
          <img ref={imgRef} src={src} alt="" draggable={false} onLoad={onLoad}
            style={{ position: 'absolute', left: 0, top: 0, width: dispW, height: dispH, transform: `translate(${off.x}px,${off.y}px)`, cursor: 'grab' }} />
          <div className="dv-crop-ring" />
        </div>
        <div className="dv-crop-controls"><span className="dv-key">Zoom</span>
          <input type="range" min="1" max="4" step="0.01" value={scale} onChange={e => setScale(parseFloat(e.target.value))} />
          <span className="dv-cmuted">drag image to reposition</span>
        </div>
        <div className="dv-modal-foot">
          <button className="dv-row-act" style={{ opacity: 1 }} onClick={onCancel}>Cancel</button>
          <button className="dv-copy-btn" onClick={save} disabled={busy || !nat}>{busy ? 'Saving…' : 'Save photo'}</button>
        </div>
      </div>
    </div>
  );
}

// Read-only details popover for a contact — opened by the ⓘ button (a click, not a hover
// tooltip). Header carries the avatar with drag-drop photo upload + reset-to-logo.
function InfoModal({ contact: c, onClose }) {
  const [ver, setVer] = useState(0);
  const [cropSrc, setCropSrc] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState(null);
  if (!c) return null;
  const row = (k, v) => (v && v !== '—') ? <div className="dv-modal-meta"><span className="dv-key">{k}</span> {v}</div> : null;
  const takeFile = f => { if (f && f.type && f.type.startsWith('image/')) { const r = new FileReader(); r.onload = () => setCropSrc(r.result); r.readAsDataURL(f); } };
  const onDrop = e => { e.preventDefault(); takeFile([...(e.dataTransfer.files || [])][0]); };
  const saveCrop = async dataUrl => {
    setBusy(true); setErr(null);
    try {
      const r = await fetch('/api/contact-photo', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: c.email, dataUrl }) });
      const j = await r.json(); if (j.error) throw new Error(j.error);
      setCropSrc(null); setVer(v => v + 1);
    } catch (e) { setErr(e.message); } finally { setBusy(false); }
  };
  const resetPhoto = async () => {
    if (!window.confirm('Remove this photo and revert to the company logo?')) return;
    setErr(null);
    try {
      const r = await fetch(`/api/contact-photo?email=${encodeURIComponent(c.email)}`, { method: 'DELETE' });
      const j = await r.json(); if (j.error) throw new Error(j.error);
      setVer(v => v + 1);
    } catch (e) { setErr(e.message); }
  };
  return (
    <div className="dv-modal-backdrop" onClick={onClose}>
      <div className="dv-modal" onClick={e => e.stopPropagation()}>
        <div className="dv-modal-head">
          <span>{c.name}{c.company ? ` · ${c.company}` : ''}</span>
          <button className="dv-modal-x" onClick={onClose} title="Close (Esc)">✕</button>
        </div>
        <div className="dv-info-top">
          <div className={`dv-avatar-drop${c.email ? '' : ' dv-avatar-drop--off'}`}
            onDragOver={c.email ? (e => e.preventDefault()) : undefined}
            onDrop={c.email ? onDrop : undefined}
            title={c.email ? 'Drop an image here to set a photo' : 'Add an email to enable a photo'}>
            <ContactAvatar c={c} size={84} version={ver} />
            {c.email && <div className="dv-avatar-hint">drop photo</div>}
          </div>
          <div className="dv-info-fields">
            {row('Title', c.title)}
            {row('Company role', c.company_role)}{row('Vertical', c.company_vertical)}
            {row('Status', c.status)}{row('Flag', c.flag)}
            {row('Email', c.email)}{row('Phone', c.phone)}
          </div>
        </div>
        {c.email && <div className="dv-avatar-actions"><button className="dv-row-act" style={{ opacity: 1 }} onClick={resetPhoto} title="Delete the custom photo and use the company logo">↺ Reset to company logo</button></div>}
        {err && <div className="dv-error" style={{ margin: '2px 16px' }}>{err}</div>}
        {row('Last contact', c.last_contact)}
        {row('Linked project', c.linked_project)}
        {row('Context', c.context)}
        {c.notes && c.notes !== '—' ? <div className="dv-modal-body-txt"><span className="dv-key">Notes</span><div>{c.notes}</div></div> : null}
      </div>
      {cropSrc && <PhotoCropper src={cropSrc} busy={busy} onCancel={() => setCropSrc(null)} onSave={saveCrop} />}
    </div>
  );
}

// Person-status vocabulary — COMPUTED at extract time from Last contact (never
// stored in the markdown): active ≤60 d · idle ≤6 mo · dormant >6 mo · uncontacted = no date.
const CONTACT_STATUSES = ['active', 'idle', 'dormant', 'uncontacted'];
// Manual overrides — the only editable state field, stored in the Flag column.
const CONTACT_FLAGS = ['do-not-contact', 'archived'];

// Add / edit a contact — writes back to Contacts.md via POST /api/contacts (which
// re-extracts contacts.json). `initial` present + has email => edit; else add.
// PERSON fields only: status is computed at extract and the company axes are
// derived from the linked company's Overview.md — neither is editable here.
function ContactForm({ initial, onClose, onSaved }) {
  const isEdit = !!(initial && initial.email);
  const [f, setF] = useState(() => ({
    Name: initial?.name || '', Email: initial?.email || '', Company: initial?.company || '',
    Title: initial?.title || '', Flag: initial?.flag || '',
    Owner: initial?.owner || '', Phone: initial?.phone || '', Context: initial?.context || '',
    'Linked project': initial?.linked_project || '', Notes: initial?.notes || '',
  }));
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState(null);
  const set = (k, v) => setF(s => ({ ...s, [k]: v }));
  const save = () => {
    if (!f.Name && !f.Email) { setErr('Name or email is required'); return; }
    setBusy(true); setErr(null);
    fetch('/api/contacts', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ op: isEdit ? 'edit' : 'add', email: initial?.email, contact: f }),
    }).then(r => r.json().then(j => ({ ok: r.ok, j })))
      .then(({ ok, j }) => { if (!ok || j.error) throw new Error(j.error || 'save failed'); onSaved(); })
      .catch(e => { setErr(e.message); setBusy(false); });
  };
  return (
    <div className="dv-modal-backdrop" onClick={onClose}>
      <div className="dv-modal" onClick={e => e.stopPropagation()}>
        <div className="dv-modal-head"><span>{isEdit ? 'Edit contact' : 'Add contact'}</span>
          <button className="dv-modal-x" onClick={onClose} title="Close">✕</button></div>
        <div className="dv-form">
          <label className="dv-form-row"><span>Name</span><input value={f.Name} onChange={e => set('Name', e.target.value)} disabled={busy} /></label>
          <label className="dv-form-row"><span>Email</span><input value={f.Email} onChange={e => set('Email', e.target.value)} disabled={busy || isEdit} /></label>
          <label className="dv-form-row"><span>Company</span><input value={f.Company} onChange={e => set('Company', e.target.value)} disabled={busy} /></label>
          <label className="dv-form-row"><span>Title</span><input value={f.Title} onChange={e => set('Title', e.target.value)} disabled={busy} /></label>
          <label className="dv-form-row" title="Manual override only — status is computed from Last contact at extract time"><span>Flag</span>
            <select value={f.Flag} onChange={e => set('Flag', e.target.value)} disabled={busy}>
              <option value="">—</option>{CONTACT_FLAGS.map(s => <option key={s} value={s}>{s}</option>)}</select></label>
          {[['Owner'], ['Phone'], ['Context'], ['Linked project'], ['Notes']].map(([k]) => (
            <label key={k} className="dv-form-row"><span>{k}</span>
              <input value={f[k]} onChange={e => set(k, e.target.value)} disabled={busy} /></label>
          ))}
        </div>
        <div className="dv-modal-foot">
          {err && <span className="dv-form-err">{err}</span>}
          <button className="dv-copy-btn" onClick={save} disabled={busy}>{busy ? 'Saving…' : (isEdit ? 'Save changes' : 'Add contact')}</button>
        </div>
      </div>
    </div>
  );
}

export function ContactsView() {
  const { selectNode } = useDashboard();
  const [data, error, reload] = useData('contacts');
  const [vert, setVert] = useState('');
  const [role, setRole] = useState('');
  const [status, setStatus] = useState('');
  const [flag, setFlag] = useState('');
  const [owner, setOwner] = useState('');
  const [q, setQ] = useState('');
  const [sort, setSort] = usePersistentState('contacts-sort', 'vertical'); // vertical|company|name|recent|draft
  // Client-side draft read-state: { [draftKey]: true } for drafts the user has "taken".
  // Keyed on email|generated so a regenerated draft flips back to unread. Fails soft
  // (usePersistentState swallows localStorage errors → everything reads as read).
  const [readDrafts, setReadDrafts] = usePersistentState('contacts-draft-read', {});
  const isUnread = useCallback(c => {
    if (!DRAFT_STATE_OK) return false;   // no persistence → treat everything as read
    const k = draftKey(c);
    return !!k && !readDrafts[k];
  }, [readDrafts]);
  const markRead = useCallback(c => {
    const k = draftKey(c);
    if (k) setReadDrafts(m => (m[k] ? m : { ...m, [k]: true }));
  }, [setReadDrafts]);
  const toggleRead = useCallback(c => {
    const k = draftKey(c);
    if (!k) return;
    setReadDrafts(m => {
      const next = { ...m };
      if (next[k]) delete next[k]; else next[k] = true;
      return next;
    });
  }, [setReadDrafts]);
  const [draftModal, setDraftModal] = useState(null);
  const [infoModal, setInfoModal] = useState(null);
  const [formContact, setFormContact] = useState(null); // null=closed, {}=add, contact=edit
  // Measure the (sticky) toolbar so the sticky column-header row can offset just beneath it,
  // staying correct when the controls wrap onto more rows.
  const toolbarRef = useRef(null);
  const [toolbarH, setToolbarH] = useState(0);
  useEffect(() => {
    const el = toolbarRef.current;
    if (!el) return;
    const measure = () => setToolbarH(el.offsetHeight);
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, [data]);

  if (isNotConfigured(error)) return <EmptyState view="Contacts" />;
  if (error) return <div className="dv-error">{error}</div>;
  if (!data) return <div className="dv-loading">Loading contacts…</div>;

  const all = data.contacts || [];
  const ql = q.trim().toLowerCase();
  // Archived rows (Flag column, manual override) are hidden unless explicitly filtered for.
  let rows = all.filter(c =>
    (c.flag !== 'archived' || flag === 'archived') &&
    (!flag || c.flag === flag) &&
    (!vert || c.company_vertical === vert) &&
    (!role || c.company_role === role) &&
    (!status || c.status === status) &&
    (!owner || (owner === '__none' ? !c.owner : c.owner === owner)) &&
    (!ql || [c.name, c.company, c.title, c.email].some(v => (v || '').toLowerCase().includes(ql)))
  );
  const byName = (a, b) => (a.name || '').localeCompare(b.name || '');
  const byVert = a => (CONTACT_VERT_ORDER.indexOf(a) + 1) || 99;
  const byStatus = a => (CONTACT_STATUSES.indexOf(a) + 1) || 99;
  if (sort === 'company') rows = [...rows].sort((a, b) => (a.company || '').localeCompare(b.company || '') || byName(a, b));
  else if (sort === 'name') rows = [...rows].sort(byName);
  else if (sort === 'recent') rows = [...rows].sort((a, b) => (b.last_contact_iso || '').localeCompare(a.last_contact_iso || '') || byName(a, b));
  else if (sort === 'draft') {
    // Drafts first: with-draft above without; within with-draft, unread above read;
    // then newest generated first; ties fall back to the default (vertical) order.
    const byDefault = (a, b) => (byVert(a.company_vertical) - byVert(b.company_vertical)) || (a.company || '').localeCompare(b.company || '') || byName(a, b);
    const draftRank = c => (c.draft ? (isUnread(c) ? 0 : 1) : 2);
    const gen = c => (c.draft && c.draft.generated) || '';
    rows = [...rows].sort((a, b) =>
      (draftRank(a) - draftRank(b)) || gen(b).localeCompare(gen(a)) || byDefault(a, b));
  }
  else rows = [...rows].sort((a, b) => (byVert(a.company_vertical) - byVert(b.company_vertical)) || (a.company || '').localeCompare(b.company || '') || byName(a, b));

  // Unread-draft count across the whole (non-archived) register, not just the filtered rows.
  const unreadCount = all.filter(c => c.flag !== 'archived' && isUnread(c)).length;
  const verts = Object.keys(data.company_verticals || {}).filter(s => s !== 'Unspecified').sort((a, b) => byVert(a) - byVert(b) || a.localeCompare(b));
  const roles = Object.keys(data.company_roles || {}).filter(s => s !== 'Unspecified').sort();
  const statuses = Object.keys(data.statuses || {}).filter(s => s !== 'Unspecified').sort((a, b) => byStatus(a) - byStatus(b) || a.localeCompare(b));
  const flags = [...new Set(all.map(c => c.flag).filter(Boolean))].sort();
  const owners = [...new Set(all.map(c => c.owner).filter(Boolean))].sort();

  const archiveContact = c => {
    if (!c.email) { window.alert('This contact needs an email before it can be archived.'); return; }
    if (!window.confirm(`Archive ${c.name || c.email}?\n\nSoft-delete — the row is kept in Contacts.md with Flag "archived" and hidden from the default view.`)) return;
    fetch('/api/contacts', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ op: 'archive', email: c.email }),
    }).then(r => r.json()).then(j => { if (j.error) window.alert(j.error); else reload(); }).catch(e => window.alert(e.message));
  };

  return (
    <div className="dv-root dv-contacts-root">
      <div className="dv-toolbar" ref={toolbarRef}>
        <input className="dv-search" placeholder="Search name / company / email…" value={q} onChange={e => setQ(e.target.value)} />
        <label className="dv-field">Sort
          <select className="dv-select" value={sort} onChange={e => setSort(e.target.value)}>
            <option value="vertical">Vertical</option>
            <option value="company">Company</option>
            <option value="name">Name (A–Z)</option>
            <option value="recent">Recent contact</option>
            <option value="draft">Drafts</option>
          </select>
        </label>
        <select className="dv-select" title="Filter by vertical (derived from the linked company's Overview)" value={vert} onChange={e => setVert(e.target.value)}>
          <option value="">All verticals ({all.length})</option>
          {verts.map(s => <option key={s} value={s}>{s} ({data.company_verticals[s]})</option>)}
        </select>
        <select className="dv-select" title="Filter by company role (derived from the linked company's Overview)" value={role} onChange={e => setRole(e.target.value)}>
          <option value="">All company roles</option>
          {roles.map(s => <option key={s} value={s}>{s} ({data.company_roles[s]})</option>)}
        </select>
        <select className="dv-select" title="Filter by status (computed from Last contact at extract time)" value={status} onChange={e => setStatus(e.target.value)}>
          <option value="">All statuses</option>
          {statuses.map(s => <option key={s} value={s}>{s} ({data.statuses[s]})</option>)}
        </select>
        {flags.length > 0 && (
          <select className="dv-select" title="Filter by manual flag — archived rows only show when selected here" value={flag} onChange={e => setFlag(e.target.value)}>
            <option value="">All (archived hidden)</option>
            {flags.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
        )}
        {owners.length > 0 && (
          <select className="dv-select" title="Filter by owner" value={owner} onChange={e => setOwner(e.target.value)}>
            <option value="">All owners</option>
            <option value="__none">Unassigned</option>
            {owners.map(o => <option key={o} value={o}>{o}</option>)}
          </select>
        )}
        <button className="dv-add-btn" onClick={() => setFormContact({})} title="Add a contact">＋ Add</button>
        {unreadCount > 0 && (
          <button className="dv-draft-count" title={`${unreadCount} new outreach draft${unreadCount === 1 ? '' : 's'} — sort by Drafts to surface them`}
            onClick={() => setSort('draft')}>✉ {unreadCount} new</button>
        )}
        <span className="dv-contacts-count">{rows.length} / {all.length}</span>
        <GeneratedStamp data={data} onReload={reload} />
      </div>

      <div className="dv-contacts-wrap" style={{ '--dv-th-top': toolbarH + 'px' }}>
        <table className="dv-contacts-table">
          <thead>
            <tr>
              <th>Name</th><th>Company</th><th>Title</th><th>Company role</th><th>Vertical</th><th>Status</th>
              <th>Last contact</th><th>Owner</th><th>Email</th><th>Project</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((c, i) => (
              <tr key={c.email || c.name || i} className={c.flag === 'do-not-contact' ? 'dv-crow--muted' : ''}>
                <td className="dv-cname">{c.name}<button className="dv-row-act dv-info-btn" title="Details" onClick={() => setInfoModal(c)}>ⓘ</button>{c.draft && <button className={`dv-draft-btn${isUnread(c) ? ' dv-draft-btn--unread' : ''}`} title={isUnread(c) ? 'View outreach draft — new (copy or mark read to clear)' : 'View outreach draft'} onClick={() => setDraftModal(c)}>✉{isUnread(c) && <span className="dv-draft-dot" />}</button>}<button className="dv-row-act" title="Edit contact" onClick={() => setFormContact(c)}>✎</button>{c.email && <button className="dv-row-act" title="Archive (soft-delete)" onClick={() => archiveContact(c)}>🗄</button>}</td>
                <td>{c.company || '—'}</td>
                <td className="dv-cmuted">{c.title || '—'}</td>
                <td>{c.company_role ? <span className="dv-badge dv-badge--role" title="Derived from the linked company's Overview (supply_chain_role) — read-only">{c.company_role}</span> : '—'}</td>
                <td>{c.company_vertical ? <span className="dv-badge dv-badge--vert" title="Derived from the linked company's Overview (vertical) — read-only">{c.company_vertical}</span> : '—'}</td>
                <td>
                  {c.status ? <span className={`dv-badge dv-badge--cstatus dv-cstatus--${cstatusSlug(c.status)}`} title="Computed from Last contact at extract time">{c.status}</span> : '—'}
                  {c.flag && <span className={`dv-badge dv-badge--cstatus dv-cstatus--${cstatusSlug(c.flag)}`} style={{ marginLeft: 4 }} title="Manual flag (Flag column)">{c.flag}</span>}
                </td>
                <td className="dv-cmuted"><FreshnessDot iso={c.last_contact_iso} /> {c.last_contact || '—'}</td>
                <td>{c.owner || <span className="dv-cmuted">—</span>}</td>
                <td>{c.email ? <a className="dv-clink" href={`mailto:${c.email}`}>{c.email}</a> : '—'}</td>
                <td>{c.linked_project ? <button className="dv-cust-chip" title={c.linked_project} onClick={() => selectNode(c.linked_project)}>↳ open</button> : <span className="dv-cmuted">—</span>}</td>
              </tr>
            ))}
            {rows.length === 0 && <tr><td colSpan={10} className="dv-empty">No contacts match.</td></tr>}
          </tbody>
        </table>
      </div>
      {draftModal && <DraftModal contact={draftModal} unread={isUnread(draftModal)}
        onMarkRead={() => markRead(draftModal)} onToggleRead={() => toggleRead(draftModal)}
        onClose={() => setDraftModal(null)} />}
      {infoModal && <InfoModal contact={infoModal} onClose={() => setInfoModal(null)} />}
      {formContact && <ContactForm initial={formContact} onClose={() => setFormContact(null)} onSaved={() => { setFormContact(null); reload(); }} />}
    </div>
  );
}

// ── Project detail — header + five slots + linked customer + timeline ────────
// Strip frontmatter + the (already-shown) TL;DR block so the timeline body isn't
// a duplicate of the card header.
function bodyForTimeline(content) {
  let b = String(content || '').replace(/^---\n[\s\S]*?\n---\n/, '');
  b = b.replace(/^##\s*TL;DR[\s\S]*?(?=^##\s)/m, '');   // drop TL;DR up to the next h2 (kept if it's the only section)
  return b.trim();
}

export function ProjectDetail({ projectId, onClose }) {
  const { selectFile, openTimeline } = useDashboard();
  const [data] = useData('projects');
  const p = useMemo(() => data?.projects?.find(x => x.id === projectId), [data, projectId]);
  const [tl, setTl] = useState({ loading: true, src: null, md: '' });

  useEffect(() => {
    if (!p) return;
    let alive = true;
    setTl({ loading: true, src: null, md: '' });
    const dir = projectId.split('/').slice(0, -1).join('/');
    const candidates = [`${dir}/Timeline.md`];
    if (p.customer_id) {
      const cdir = p.customer_id.split('/').slice(0, -1).join('/');
      candidates.push(`${cdir}/Timeline.md`);
    }
    candidates.push(projectId);   // last resort: the Overview body's dated history
    (async () => {
      for (const path of candidates) {
        try {
          const r = await fetch(`/api/files?path=${encodeURIComponent(path)}`);
          if (!r.ok) continue;
          const d = await r.json();
          const md = path === projectId ? bodyForTimeline(d.content) : (d.content || '').trim();
          if (md) { if (alive) setTl({ loading: false, src: path, md }); return; }
        } catch { /* try next */ }
      }
      if (alive) setTl({ loading: false, src: null, md: '' });
    })();
    return () => { alive = false; };
  }, [projectId, p && p.customer_id]);

  if (!p) return <div className="dv-detail"><div className="dv-loading">Loading…</div></div>;
  const dotIso = p.card_date_is_mtime ? null : p.card_date_iso;
  const isSub = !!p.parent_id;

  return (
    <div className="dv-detail">
      <div className="dv-detail-head">
        <Logo slug={p.logo_slug} name={p.customer_name || p.name} size={34} />
        <div className="dv-detail-title">
          <div className="dv-detail-name">{p.name}</div>
          <div className="dv-detail-badges">
            {isSub
              ? (p.customer_name && <span className="dv-badge dv-badge--inherit">↳ {p.customer_name}{p.customer_tier ? ` · T${p.customer_tier}` : ''}</span>)
              : (p.tier && <span className="dv-badge dv-badge--tier">T{p.tier}</span>)}
            {p.vertical && <span className="dv-badge dv-badge--vert">{p.vertical}</span>}
            {p.phase && <span className={`dv-badge dv-badge--phase dv-badge--phase-${p.phase}`}>{p.phase}</span>}
            {p.node_kind === 'product-parent' && <span className="dv-badge">product line</span>}
          </div>
        </div>
        <div className="dv-detail-actions">
          <button className="btn btn-sm" title="Open the raw Overview.md" onClick={() => selectFile(p.id)}>↗ Overview</button>
          <button className="btn-close" onClick={onClose}>&times;</button>
        </div>
      </div>

      <dl className="dv-detail-slots">
        {p.description && <div className="dv-slot"><dt className="dv-key">Scope</dt><dd className="dv-val">{p.description}</dd></div>}
        {p.card_status && <div className="dv-slot"><dt className="dv-key">State</dt><dd className="dv-val">{p.card_status}</dd></div>}
        {p.tldr?.next_milestone && <div className="dv-slot"><dt className="dv-key">Next</dt><dd className="dv-val">{p.tldr.next_milestone}</dd></div>}
        {p.tldr?.open_blockers && <div className="dv-slot"><dt className="dv-key">Blocker</dt><dd className="dv-val dv-val--blocker">{p.tldr.open_blockers}</dd></div>}
        <div className="dv-slot">
          <dt className="dv-key">Last</dt>
          <dd className="dv-val"><FreshnessDot iso={dotIso} /> {p.card_date_iso || '—'}{p.card_date_is_mtime ? ' (file modified)' : ''}</dd>
        </div>
        {isSub && p.customer_id && (
          <div className="dv-slot"><dt className="dv-key">Customer</dt>
            <dd className="dv-val"><button className="dv-cust-chip" onClick={() => openTimeline(p.customer_id)}>{p.customer_name} ↗</button></dd>
          </div>
        )}
        {p.subproject_ids?.length > 0 && (
          <div className="dv-slot"><dt className="dv-key">Builds</dt>
            <dd className="dv-val">{p.subproject_ids.map(id => {
              const c = data?.projects?.find(x => x.id === id);
              return c ? <button key={id} className="dv-cust-chip" onClick={() => openTimeline(id)}>{c.name} ↗</button> : null;
            })}</dd>
          </div>
        )}
        {p.customer_build_ids?.length > 0 && (
          <div className="dv-slot"><dt className="dv-key">Customer builds</dt>
            <dd className="dv-val">{p.customer_build_ids.map(id => {
              const c = data?.projects?.find(x => x.id === id);
              return c ? <button key={id} className="dv-cust-chip" onClick={() => openTimeline(id)}>{c.name} ↗</button> : null;
            })}</dd>
          </div>
        )}
      </dl>

      <div className="dv-detail-timeline">
        <div className="dv-detail-tl-head">
          Timeline {tl.src && tl.src !== projectId && <span className="dv-stamp">from {tl.src.split('/').pop()}</span>}
        </div>
        {tl.loading ? <div className="dv-loading">Loading timeline…</div>
          : tl.md ? <div className="markdown-body"><Markdown remarkPlugins={[remarkGfm]}>{tl.md}</Markdown></div>
          : <div className="dv-empty">No timeline content yet — add a dated history to this Overview or a sibling Timeline.md.</div>}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sync — the weekly Sales & Operations sync as a board
// ---------------------------------------------------------------------------

function PartnerCard({ p }) {
  const [open, setOpen] = useState(false);
  // New (category-first, 2026-06) entities carry flat fields; old (company-first)
  // weeks carry rows[]/actions[]. Support both so the week-nav history renders.
  const legacy = Array.isArray(p.rows);
  const last = legacy ? p.rows.find(r => /last engagement/i.test(r.topic)) : null;
  const phase = legacy ? p.rows.find(r => /project phase|phase/i.test(r.topic)) : null;
  const freshIso = legacy ? last?.date_iso : p.date_iso;
  const engageDate = legacy ? last?.date_raw : p.date_raw;
  const engageText = legacy ? last?.content : p.last_engagement;
  const statusText = legacy ? phase?.content : p.status;
  const expandable = legacy && p.rows.length > 0;   // only old weeks have a rows table to reveal
  return (
    <div className="dv-card dv-card--partner">
      <div className="dv-card-head" onClick={() => expandable && setOpen(v => !v)} style={{ cursor: expandable ? 'pointer' : 'default' }}>
        <FreshnessDot iso={freshIso} />
        <span className="dv-card-name">{p.name}</span>
        {p.group && <span className="dv-badge">{p.group.replace(/\s*\*.*\*$/, '')}</span>}
        {expandable && <span className="dv-card-caret">{open ? '▾' : '▸'}</span>}
      </div>
      {p.descriptor && <div className="dv-card-desc">{p.descriptor}</div>}
      {engageText && <div className="dv-card-line"><span className="dv-key">{engageDate || 'Last'}:</span> {engageText}</div>}
      {statusText && (!legacy || !open) && <div className="dv-card-line"><span className="dv-key">Status:</span> {statusText}</div>}
      {open && expandable && (
        <>
          <table className="dv-table">
            <tbody>
              {p.rows.map((r, i) => (
                <tr key={i}><td className="dv-key">{r.topic}</td><td>{r.content}</td><td className="dv-date">{r.date_raw}</td></tr>
              ))}
            </tbody>
          </table>
          {p.actions && p.actions.length > 0 && (
            <ul className="dv-actions">
              {p.actions.map((a, i) => (
                <li key={i} className={a.external ? 'dv-action--ext' : ''}>
                  {a.external && <span className="dv-badge dv-badge--ext">ext</span>} {a.item}
                </li>
              ))}
            </ul>
          )}
        </>
      )}
    </div>
  );
}

function SectionTable({ rows }) {
  if (!rows || rows.length === 0) return null;
  const keys = Object.keys(rows[0]).filter(k => !k.endsWith('_iso'));
  return (
    <table className="dv-table dv-table--full">
      <thead><tr>{keys.map(k => <th key={k}>{k.replace(/_/g, ' ')}</th>)}</tr></thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i}>{keys.map(k => <td key={k}>{r[k]}</td>)}</tr>
        ))}
      </tbody>
    </table>
  );
}

// Render the displayed week's Sales & Operations sync to PDF. The server shells
// out to scripts/sync-report-pdf.js for the given week (YYYYMMDD); if `week` is
// missing/malformed it omits the arg and the script falls back to the latest week.
// status: idle | rendering | done | locked | error
function RenderPdfButton({ week }) {
  const { selectFile } = useDashboard();
  const [pdf, setPdf] = useState({ status: 'idle', msg: '' });
  const resetTimer = useRef(null);
  const wk = /^\d{8}$/.test(String(week || '')) ? String(week) : null;

  // One pending auto-reset at a time: a new render cancels the prior render's
  // reset so a stale 6 s timer can't blank a fresh result early; cleared on unmount.
  useEffect(() => () => clearTimeout(resetTimer.current), []);

  const renderPdf = async () => {
    if (pdf.status === 'rendering') return;
    clearTimeout(resetTimer.current);
    setPdf({ status: 'rendering', msg: '' });
    try {
      const res = await fetch('/api/render-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(wk ? { week: wk } : {}),
      });
      const raw = await res.text();
      let resp = {};
      try { resp = JSON.parse(raw); } catch { /* non-JSON (e.g. 404 HTML) */ }
      if (res.ok) {
        setPdf({ status: 'done', msg: resp.message || 'PDF written' });
        // Auto-open the freshly rendered PDF in the right-hand FileViewer.
        if (resp.pdfPath) selectFile(resp.pdfPath);
      } else if (res.status === 404) {
        setPdf({ status: 'error', msg: 'Endpoint not found (HTTP 404) — restart the dashboard server so /api/render-pdf loads' });
      } else if (res.status === 423 || resp.locked) {
        setPdf({ status: 'locked', msg: 'PDF is open/locked — close the viewer and retry' });
      } else {
        setPdf({ status: 'error', msg: resp.message || `Render failed (HTTP ${res.status})` });
      }
    } catch (e) {
      setPdf({ status: 'error', msg: String(e.message || e) });
    }
    resetTimer.current = setTimeout(() => setPdf(p => (p.status === 'rendering' ? p : { status: 'idle', msg: '' })), 6000);
  };

  const label = pdf.status === 'rendering' ? 'Rendering…'
    : pdf.status === 'done' ? '✓ PDF saved'
    : pdf.status === 'locked' ? '⚠ PDF locked'
    : pdf.status === 'error' ? '✕ PDF failed'
    : '⤓ Render PDF';
  const stateClass = pdf.status === 'done' ? 'dv-pdfbtn--done'
    : pdf.status === 'locked' ? 'dv-pdfbtn--locked'
    : pdf.status === 'error' ? 'dv-pdfbtn--error'
    : '';

  return (
    <>
      <button
        className={`dv-pdfbtn ${stateClass}`}
        onClick={renderPdf}
        disabled={pdf.status === 'rendering'}
        title={pdf.msg || (wk ? `Render the week of ${week} to PDF` : 'Render the latest weekly Sales & Operations sync to PDF')}
      >
        {label}
      </button>
      {(pdf.status === 'error' || pdf.status === 'locked') && pdf.msg && (
        <span className={`dv-pdfmsg dv-pdfmsg--${pdf.status}`} title={pdf.msg}>
          {pdf.msg}
        </span>
      )}
    </>
  );
}

// ---------------------------------------------------------------------------
// Sync — verticals view
//
// The category-first weekly sync (Sync_Content_Schema §J) tags every
// SALES/OPERATIONS entity with a `group` like "FOUNDRY — Design" /
// "EQUIPMENT — Testers". This view pivots those rows into the 2026 website's
// product lenses — the "how we sell" view, complementing the company-first
// Projects tab (which stays entity-centric). It splits each group on the
// em-dash " — " (left = vertical, right = focus) and lays the entities out as
// four lanes, each an accordion per focus group. PartnerCard/FreshnessDot are
// reused unchanged; the flat list stays the default and the fallback.
// ---------------------------------------------------------------------------

// The four product lanes (mirror the website verticals). `accent` colours echo
// the graph layer-hue family (blue→violet→cyan→magenta) and deliberately avoid
// the green/amber/red of FreshnessDot, so a lane accent never reads as a
// freshness signal.
const VERTICAL_LANES = [
  { key: 'EQUIPMENT', label: 'Equipment', accent: '#3b82f6' },
  { key: 'FOUNDRY',   label: 'Foundry',   accent: '#8b5cf6' },
  { key: 'PRODUCTS',  label: 'Products',  accent: '#06b6d4' },
  { key: 'AI',        label: 'AI',        accent: '#ec4899' },
];

// Canonical focus order within each lane. Any focus not listed sorts after these
// alphabetically, so a newly-introduced focus group still appears (at the end).
const FOCUS_ORDER = {
  EQUIPMENT: ['Testers', 'DLW', 'Strategic & Equipment Placement'],
  FOUNDRY:   ['Design', 'Fabrication', 'Capex / Internal'],
  PRODUCTS:  ['Consumer Devices', 'Camera Modules'],
  AI:        ['AI & Software'],
};

// Split a sync `group` into { lane, focus }. Most groups are "VERTICAL — Focus".
// Two carry no " — " separator and no website vertical of their own:
//   • "AI & SOFTWARE"               → the AI lane, single "AI & Software" focus.
//   • "STRATEGIC & EQUIPMENT PLACEMENT" → FOLDED INTO the Equipment lane as its own
//     "Strategic & Equipment Placement" focus accordion. Rationale: these are
//     research/strategic partners HOSTING a MOT tool (a DLW or tester), so the
//     loaned artefact is MOT *equipment* — the Equipment lane is its natural
//     home. It stays a separate accordion (not merged into Testers/DLW) because
//     it is a relationship type, not a sales focus. Folding here keeps the
//     deliberate four-lane layout rather than spawning a lone 5th lane for the
//     one group that maps to no website vertical.
function laneAndFocus(group) {
  if (!group) return { lane: null, focus: null };
  const parts = group.split(/\s*—\s*/);             // em-dash separator
  const vertical = (parts[0] || '').trim();
  const focus = parts.slice(1).join(' — ').trim();  // keep a focus that itself had a dash
  const v = vertical.toUpperCase();
  if (v.startsWith('STRATEGIC')) return { lane: 'EQUIPMENT', focus: 'Strategic & Equipment Placement' };
  if (v.startsWith('FOUNDRY'))   return { lane: 'FOUNDRY',   focus: focus || 'Design' };
  if (v.startsWith('EQUIPMENT')) return { lane: 'EQUIPMENT', focus: focus || 'General' };
  if (v.startsWith('PRODUCTS'))  return { lane: 'PRODUCTS',  focus: focus || 'General' };
  if (v.startsWith('AI'))        return { lane: 'AI',        focus: focus || 'AI & Software' };
  return { lane: null, focus: focus || vertical || null };
}

function orderedFocuses(laneKey, focuses) {
  const order = FOCUS_ORDER[laneKey] || [];
  const inOrder = order.filter(f => focuses.includes(f));
  const extras = focuses.filter(f => !order.includes(f)).sort();
  return [...inOrder, ...extras];
}

// One focus group inside a lane — a collapsible list of PartnerCards. Open state
// persists per (section, lane, focus) so it survives reloads and week switches.
function FocusAccordion({ storageKey, label, partners }) {
  const [open, setOpen] = usePersistentState(storageKey, true);
  return (
    <div className="dv-facc">
      <button className="dv-facc-head" onClick={() => setOpen(o => !o)} aria-expanded={open}>
        <span className="dv-facc-caret">{open ? '▾' : '▸'}</span>
        <span className="dv-facc-label">{label}</span>
        <span className="dv-count">{partners.length}</span>
      </button>
      {open && (
        <div className="dv-facc-body">
          {partners.map(p => <PartnerCard key={(p.group || '') + p.name} p={p} />)}
        </div>
      )}
    </div>
  );
}

// Four product lanes for one grouped section's partners. Entities whose group is
// unrecognised / missing fall into a full-width "Other" strip below the lanes
// rather than being silently dropped.
function VerticalLanes({ sectionName, partners }) {
  const { byLane, ungrouped } = useMemo(() => {
    const byLane = {};
    for (const lane of VERTICAL_LANES) byLane[lane.key] = {};
    const ungrouped = [];
    for (const p of partners) {
      const { lane, focus } = laneAndFocus(p.group);
      if (!lane || !byLane[lane]) { ungrouped.push(p); continue; }
      const f = focus || 'General';
      (byLane[lane][f] ||= []).push(p);
    }
    return { byLane, ungrouped };
  }, [partners]);

  return (
    <>
      <div className="dv-vlanes">
        {VERTICAL_LANES.map(lane => {
          const groups = byLane[lane.key];
          const focuses = orderedFocuses(lane.key, Object.keys(groups));
          const total = focuses.reduce((n, f) => n + groups[f].length, 0);
          return (
            <div key={lane.key} className="dv-vlane" style={{ '--lane-accent': lane.accent }}>
              <div className="dv-vlane-head">
                <span className="dv-vlane-title">{lane.label}</span>
                <span className="dv-count">{total}</span>
              </div>
              {focuses.length === 0
                ? <div className="dv-vlane-empty">No active entries this week</div>
                : focuses.map(focus => (
                    <FocusAccordion
                      key={focus}
                      storageKey={`sync-vert-acc:${sectionName}:${lane.key}:${focus}`}
                      label={focus}
                      partners={groups[focus]}
                    />
                  ))}
            </div>
          );
        })}
      </div>
      {ungrouped.length > 0 && (
        <div className="dv-vlane dv-vlane--ungrouped" style={{ '--lane-accent': 'var(--text-muted)' }}>
          <div className="dv-vlane-head">
            <span className="dv-vlane-title">Other</span>
            <span className="dv-count">{ungrouped.length}</span>
          </div>
          <div className="dv-facc-body">
            {ungrouped.map(p => <PartnerCard key={(p.group || '') + p.name} p={p} />)}
          </div>
        </div>
      )}
    </>
  );
}

// Sort a section's partner cards for the Sync tab. `default` keeps document
// order; date sorts push undated rows last; `importance` uses a project-tier
// lookup (tierFn, built from projects.json) so focus accounts surface first.
// Returns the same array reference for `default` so React skips needless work.
function sortSyncPartners(partners, sort, tierFn) {
  if (!sort || sort === 'default') return partners;
  const byName = (a, b) => a.name.localeCompare(b.name);
  const arr = [...partners];
  if (sort === 'name') arr.sort(byName);
  else if (sort === 'importance') arr.sort((a, b) =>
    (tierFn(a.name) || 9) - (tierFn(b.name) || 9) || (b.date_iso || '').localeCompare(a.date_iso || '') || byName(a, b));
  else { // newest | oldest — undated rows always last
    const dir = sort === 'oldest' ? 1 : -1;
    arr.sort((a, b) => {
      const da = a.date_iso, db = b.date_iso;
      if (!da && !db) return byName(a, b);
      if (!da) return 1;
      if (!db) return -1;
      return dir * da.localeCompare(db) || byName(a, b);
    });
  }
  return arr;
}

export function SyncView() {
  const { selectFile } = useDashboard();
  const [mode, setMode] = usePersistentState('sync-view-mode', 'flat');  // flat (default) ↔ verticals
  // Published weeks, newest → oldest (from sync-weeks.json). weeks[0] is the
  // current/active week; default the selector to it. Per-week sync content
  // lives at /api/data/sync/<week>.json (sync.json is the latest, kept as a
  // fallback until the index loads).
  const [weeksData] = useData('sync-weeks');
  const weeks = Array.isArray(weeksData?.weeks) ? weeksData.weeks : [];
  const activeWeek = weeks[0]?.week || null;
  const [viewWeek, setViewWeek] = useState(null);   // null → the current (newest) week
  const week = viewWeek || activeWeek;
  const [data, error, reload] = useData(week ? `sync/${week}` : 'sync');
  const [sort, setSort] = usePersistentState('sync-sort', 'default'); // default|newest|oldest|importance|name
  const [projData] = useData('projects');           // for the "importance" sort (project tier by name)
  const tierFn = useMemo(() => {
    const idx = new Map();
    for (const p of (projData?.projects || [])) if (p.tier != null) idx.set(normName(p.name), p.tier);
    return (name) => {
      const n = normName(name);
      if (idx.has(n)) return idx.get(n);
      const nt = n.split(' ').filter(x => x.length > 2);   // token-overlap fallback (e.g. "ST Micro" → STMicro…)
      for (const [k, t] of idx) { const kt = k.split(' '); if (kt.some(x => x.length > 2 && nt.includes(x))) return t; }
      return 9;                                            // unmatched (e.g. OPERATIONS workstreams) sort last
    };
  }, [projData]);
  if (isNotConfigured(error)) return <EmptyState view="Sync" />;
  if (error) return <div className="dv-error">{error}</div>;
  if (!data) return <div className="dv-loading">Loading sync…</div>;

  const curWeek = week || data.week;
  const idx = weeks.findIndex(w => w.week === curWeek);   // -1 until the index loads
  const isCurrent = idx <= 0;                              // newest week (or single-file fallback)
  const isDraft = idx >= 0 ? !!weeks[idx].draft : !!data.draft;  // ongoing in-preparation week

  return (
    <div className="dv-root">
      <div className="dv-toolbar">
        <span className="dv-title">Sales &amp; Operations sync</span>
        <div className="dv-weeknav">
          <button className="dv-weekbtn" disabled={idx < 0 || idx >= weeks.length - 1}
            title="Older week" onClick={() => setViewWeek(weeks[idx + 1].week)}>◀</button>
          <span className="dv-weeklabel">week of {weekIso(curWeek)}{isDraft && ' · draft'}</span>
          <button className="dv-weekbtn" disabled={idx <= 0}
            title="Newer week" onClick={() => setViewWeek(weeks[idx - 1].week)}>▶</button>
        </div>
        <div className="dv-seg" role="group" aria-label="Sync layout">
          <button className={`dv-segbtn ${mode === 'flat' ? 'dv-segbtn--on' : ''}`}
            onClick={() => setMode('flat')} title="Flat list — every entity under its section">Flat</button>
          <button className={`dv-segbtn ${mode === 'verticals' ? 'dv-segbtn--on' : ''}`}
            onClick={() => setMode('verticals')}
            title="Verticals — group SALES/OPERATIONS by product lane (Equipment / Foundry / Products / AI)">Verticals</button>
        </div>
        <label className="dv-field">Sort
          <select className="dv-select" value={sort} onChange={e => setSort(e.target.value)}
            title="Sort partner cards within each section / focus group">
            <option value="default">Default</option>
            <option value="newest">Newest</option>
            <option value="oldest">Oldest</option>
            <option value="importance">Importance</option>
            <option value="name">Name (A–Z)</option>
          </select>
        </label>
        <button className="dv-chip" onClick={() => selectFile(data.source)}>open report</button>
        {!isDraft && <RenderPdfButton week={data.week} />}
        <GeneratedStamp data={data} onReload={reload} />
        {isDraft
          ? <span className="dv-stamp">in preparation — not yet published</span>
          : !isCurrent && <span className="dv-stamp">viewing an earlier published week</span>}
      </div>
      {data.sections.map(sec => {
        const partners = sortSyncPartners(sec.partners, sort, tierFn);
        return (
        <div key={sec.name} className="dv-section">
          <h2 className="dv-h2">{sec.name}</h2>
          {sec.descriptor && <div className="dv-card-desc">{sec.descriptor}</div>}
          {sec.bulletGroups && sec.bulletGroups.length > 0 ? (
            sec.bulletGroups.map((g, gi) => (
              <div key={gi} className="dv-bulletgroup">
                <h3 className="dv-h3">{g.label}</h3>
                <ul className="dv-bullets">{g.items.map((b, i) => <li key={i}>{b}</li>)}</ul>
              </div>
            ))
          ) : sec.bullets.length > 0 && (
            <ul className="dv-bullets">{sec.bullets.map((b, i) => <li key={i}>{b}</li>)}</ul>
          )}
          <SectionTable rows={sec.table} />
          {/* DIRECTION / EVENTS / GENERAL / Backlog tables carry no `group`, so
              their partners[] is empty — this branch only affects SALES /
              OPERATIONS. Flat is the default + the fallback for any week. */}
          {partners.length > 0 && (
            mode === 'verticals'
              ? <VerticalLanes sectionName={sec.name} partners={partners} />
              : (
                <div className="dv-cardgrid">
                  {partners.map(p => <PartnerCard key={(p.group || '') + p.name} p={p} />)}
                </div>
              )
          )}
        </div>
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// To-Do — person columns + external pending + key dates
// ---------------------------------------------------------------------------

// A source to-do section whose name matches this is the team / unassigned
// bucket (e.g. "## Unassigned / team"). It becomes the pinned first column
// rather than a per-person column — and we never synthesize a second one.
const TEAM_RE = /unassigned|team/i;

// Week-id math (YYYYMMDD). Browser Date is fine here (not a workflow script).
function shiftWeek(weekId, days) {
  const dt = new Date(+weekId.slice(0, 4), +weekId.slice(4, 6) - 1, +weekId.slice(6, 8));
  dt.setDate(dt.getDate() + days);
  const p = n => String(n).padStart(2, '0');
  return `${dt.getFullYear()}${p(dt.getMonth() + 1)}${p(dt.getDate())}`;
}
const weekIso = weekId => `${weekId.slice(0, 4)}-${weekId.slice(4, 6)}-${weekId.slice(6, 8)}`;

export function TodosView() {
  const { selectFile } = useDashboard();
  const [data, error, reload] = useData('todos');
  const [store, setStore] = useState({ version: 2, weeks: {} }); // week-scoped overlay
  const [viewWeek, setViewWeek] = useState(null);    // null → the active (current) week
  const [dragOver, setDragOver] = useState(null);    // owner column under cursor
  const [hideClosed, setHideClosed] = useState(false); // hide resolved + deleted
  const [showRemoved, setShowRemoved] = useState(false); // reveal tasks confirmed-removed from the report
  const [addingIn, setAddingIn] = useState(null);    // owner whose add-task input is open
  const [newText, setNewText] = useState('');
  const dragged = useRef(null);                      // {id, text, basePerson}
  const dragGhost = useRef(null);                    // detached solid drag-image element
  const grabOffset = useRef({ x: 0, y: 0 });         // cursor offset within the grabbed tile
  const addCancel = useRef(false);                   // Esc pressed → blur should not create

  // Load the durable overlay (not cached — it mutates as we edit).
  useEffect(() => {
    fetch('/api/assignments')
      .then(r => r.ok ? r.json() : { weeks: {} })
      .then(d => setStore(d.weeks ? d : { version: 2, weeks: {} }))
      .catch(() => setStore({ version: 2, weeks: {} }));
  }, []);

  const activeWeek = data?.week || null;             // the week todos.json projects
  const week = viewWeek || activeWeek;               // currently viewed week
  const isFuture = !!(week && activeWeek && week > activeWeek);
  const edits = (week && store.weeks?.[week]?.edits) || {};   // this week's deltas

  // The canonical team bucket: the existing source section if there is one,
  // else a synthetic "Unassigned" label. Dropping on the first column writes
  // this exact value, so propagation maps it straight back to that heading.
  const team = useMemo(
    () => (data ? Object.keys(data.by_person).find(k => TEAM_RE.test(k)) || 'Unassigned' : 'Unassigned'),
    [data]);

  // Base tasks for the *active* week, straight from the markdown projection.
  const activeBase = useMemo(() => {
    if (!data) return [];
    return Object.entries(data.by_person).flatMap(([basePerson, items]) =>
      // Back-compat: pre-id extracts stored bare strings.
      items.map(it => typeof it === 'string'
        ? { id: null, text: it, basePerson }
        : { id: it.id, text: it.text, basePerson }));
  }, [data]);

  // Base for the viewed week. The active week uses the markdown projection; a
  // future week previews the carry-over: the active week's still-open tasks at
  // their current owner. Tasks resolved or deleted this week fall off here — the
  // publish-gated removal the report needs (they stay green in the active week).
  const baseForView = useMemo(() => {
    if (!data || !week) return [];
    if (week <= activeWeek) return activeBase;
    const e = store.weeks?.[activeWeek]?.edits || {};
    const dropped = new Set(Object.values(e).filter(x => x.deleted || x.dismissed || x.status === 'done').map(x => x.id));
    const own = t => (t.id && e[t.id]?.to) || t.basePerson;
    const created = Object.values(e).filter(x => x.created && !x.deleted && x.status !== 'done')
      .map(x => ({ id: x.id, text: x.text, basePerson: x.to }));
    return [...activeBase, ...created]
      .filter(t => !t.id || !dropped.has(t.id))
      .map(t => ({ id: t.id, text: t.text, basePerson: own(t) }));
  }, [data, week, activeWeek, activeBase, store]);

  // Layer this week's overlay on the base, then append created tasks. Deleted
  // tasks stay visible (shaded red) until the next publish drops them; they're
  // only removed from a *future* week's carry-over (handled in baseForView).
  const tasks = useMemo(() => {
    const created = Object.values(edits)
      .filter(a => a.created)
      .map(a => ({ id: a.id, text: a.text, basePerson: a.to, created: true }));
    return [...baseForView, ...created];
  }, [baseForView, edits]);

  const ownerOf = t => (t.id && edits[t.id]?.to) || t.basePerson;
  const isDone = t => t.id && edits[t.id]?.status === 'done';
  const isDeleted = t => t.id && edits[t.id]?.deleted;
  const isDismissed = t => t.id && edits[t.id]?.dismissed;   // step-2 confirmed: off the report now

  // Column order: team first (pinned), then the agent's people, then any owner
  // an overlay edit introduced. Single row — horizontal scroll past the pin.
  const columns = useMemo(() => {
    if (!data) return [];
    const people = Object.keys(data.by_person).filter(p => p !== team);
    for (const a of Object.values(edits)) if (a.to && a.to !== team && !people.includes(a.to)) people.push(a.to);
    return [team, ...people];
  }, [data, edits, team]);

  const pending = Object.values(edits).filter(a => !a.propagated).length;
  const removedCount = tasks.filter(t => isDismissed(t)).length;

  // Mirror of the server's applyOp on one week's edit map: optimistically merge
  // a delta and prune it if it reverts to base, so the UI matches what persists.
  function applyEditsLocal(prevEdits, op) {
    const next = { ...prevEdits };
    const id = op.id;
    const cur = next[id] || {};
    const merged = {
      id,
      text: op.text ?? cur.text ?? '',
      from: op.from ?? cur.from ?? null,
      to: op.to ?? cur.to ?? null,
      status: op.status ?? cur.status ?? 'open',
      created: op.created ?? cur.created ?? false,
      deleted: op.deleted ?? cur.deleted ?? false,
      dismissed: op.dismissed ?? cur.dismissed ?? false,
      propagated: false,
    };
    const noop = !merged.created && !merged.deleted && !merged.dismissed && merged.status === 'open' && merged.to === merged.from;
    if (noop) delete next[id]; else next[id] = merged;
    return next;
  }

  // Post an edit tagged to the viewed week; optimistic when the id is known,
  // otherwise (create) wait for the server to mint it. Reconciles with the response.
  function postOp(op) {
    op = { ...op, week };
    if (op.id) setStore(prev => {
      const next = { ...prev, weeks: { ...prev.weeks } };
      const bucket = { published: false, ...(next.weeks[week] || {}) };
      bucket.edits = applyEditsLocal({ ...(bucket.edits || {}) }, op);
      next.weeks[week] = bucket;
      return next;
    });
    fetch('/api/assignments', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(op),
    })
      .then(r => r.ok ? r.json() : Promise.reject())
      .then(d => setStore(d.store || { version: 2, weeks: {} }))
      .catch(() => {                                     // refetch authoritative state on failure
        fetch('/api/assignments').then(r => r.json()).then(d => setStore(d.weeks ? d : { version: 2, weeks: {} })).catch(() => {});
      });
  }

  // Move the floating drag preview, holding the same grab point under the cursor
  // (so the tile travels relative to where you clicked, not top-left snapped). The
  // browser fires a final `drag` at (0,0) on release — ignore it so it doesn't jump.
  function positionGhost(x, y) {
    const g = dragGhost.current;
    if (!g || (x === 0 && y === 0)) return;
    g.style.left = `${x - grabOffset.current.x}px`;
    g.style.top = `${y - grabOffset.current.y}px`;
  }

  // Tear down a drag from whichever handler fires first (drop relocates the
  // source node, so dragend is unreliable — clean up in both).
  function cleanupDrag() {
    if (dragGhost.current) { dragGhost.current.remove(); dragGhost.current = null; }
    dragged.current = null;
    setDragOver(null);
  }

  function onDrop(owner) {
    const t = dragged.current;
    cleanupDrag();
    if (!t || !t.id || owner === ownerOf(t)) return;   // no-op / un-id'd legacy task
    // `from` is the agent's base assignment so the propagation diff compares
    // against the source markdown, not prior drags. For created tasks basePerson
    // is their home column, so dropping back there is still a no-op revert.
    postOp({ id: t.id, text: t.text, from: t.basePerson, to: owner });
  }

  const toggleDone = t => postOp({ id: t.id, text: t.text, status: isDone(t) ? 'open' : 'done' });
  const toggleDeleted = t => postOp({ id: t.id, text: t.text, deleted: !isDeleted(t) });
  // Step 2: confirm a marked (green/red) task off the current report immediately.
  const confirmRemove = t => postOp({ id: t.id, text: t.text, dismissed: true });
  // Pull a removed task all the way back to open (clears done/deleted/dismissed).
  const restoreTask = t => postOp({ id: t.id, text: t.text, status: 'open', deleted: false, dismissed: false });

  // Single creation path: the textarea's onBlur. Enter/blur-away commit; Esc
  // sets addCancel so the ensuing blur discards instead of creating.
  function commitNewTask(owner) {
    const cancelled = addCancel.current;
    addCancel.current = false;
    const text = newText.trim();
    setNewText('');
    setAddingIn(null);
    if (!cancelled && text) postOp({ text, to: owner, created: true });
  }

  function renderColumn(owner) {
    const all = tasks.filter(t => ownerOf(t) === owner);
    const closed = t => isDone(t) || isDeleted(t);
    // Removed (dismissed) tasks are off the report — hidden unless the toolbar
    // "show removed" toggle is on. done/deleted are still governed by hideClosed.
    const colTasks = all.filter(t => {
      if (isDismissed(t)) return showRemoved;
      return !(hideClosed && closed(t));
    });
    const openCount = all.filter(t => !closed(t) && !isDismissed(t)).length;
    const isTeam = owner === team;
    return (
      <div
        key={owner}
        className={`dv-col ${dragOver === owner ? 'dv-col--over' : ''} ${isTeam ? 'dv-col--team' : ''}`}
        onDragOver={e => { e.preventDefault(); if (dragOver !== owner) setDragOver(owner); }}
        onDragLeave={e => { if (e.currentTarget === e.target) setDragOver(null); }}
        onDrop={() => onDrop(owner)}
      >
        <h3 className="dv-h3">
          {isTeam ? 'Team tasks' : owner} <span className="dv-count">{openCount}</span>
          <button className="dv-add" title="Add a task to this column" onClick={() => { setAddingIn(owner); setNewText(''); }}>+</button>
        </h3>
        <div className="dv-col-body">
          {addingIn === owner && (
            <textarea
              className="dv-add-input"
              autoFocus
              rows={4}
              placeholder="New task… (Enter to add, Esc to cancel)"
              value={newText}
              onChange={e => setNewText(e.target.value)}
              onKeyDown={e => {
                if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); e.currentTarget.blur(); }
                else if (e.key === 'Escape') { addCancel.current = true; e.currentTarget.blur(); }
              }}
              onBlur={() => commitNewTask(owner)}
            />
          )}
          {colTasks.map((t, i) => {
            const moved = t.id && edits[t.id]?.to && edits[t.id].to !== t.basePerson;
            const done = isDone(t);
            const deleted = isDeleted(t);
            const dismissed = isDismissed(t);
            return (
              <div
                key={t.id || i}
                className={`dv-task ${t.id ? '' : 'dv-task--legacy'} ${moved ? 'dv-task--moved' : ''} ${done ? 'dv-task--done' : ''} ${deleted ? 'dv-task--deleted' : ''} ${dismissed ? 'dv-task--dismissed' : ''} ${t.created ? 'dv-task--created' : ''}`}
                draggable={!!t.id && !dismissed}
                onDragStart={e => {
                  if (dragGhost.current) { dragGhost.current.remove(); dragGhost.current = null; }
                  dragged.current = t;
                  e.dataTransfer.effectAllowed = 'move';
                  // Suppress the browser's native drag image (it's translucent and
                  // gradient-faded, not controllable) with a 1px blank canvas…
                  const blank = document.createElement('canvas');
                  blank.width = blank.height = 1;
                  e.dataTransfer.setDragImage(blank, 0, 0);
                  // …then follow the cursor with our own fully-opaque solid clone,
                  // holding the exact point within the tile where you grabbed it.
                  const card = e.currentTarget;
                  const rect = card.getBoundingClientRect();
                  grabOffset.current = { x: e.clientX - rect.left, y: e.clientY - rect.top };
                  const ghost = card.cloneNode(true);
                  ghost.classList.add('dv-drag-ghost');
                  ghost.style.width = `${card.offsetWidth}px`;
                  document.body.appendChild(ghost);
                  dragGhost.current = ghost;
                  positionGhost(e.clientX, e.clientY);
                }}
                onDrag={e => positionGhost(e.clientX, e.clientY)}
                onDragEnd={cleanupDrag}
                title={t.id ? 'Drag to reassign' : 'Re-run extract to enable reassignment'}
              >
                <span className="dv-task-text">{t.text}</span>
                {t.id && (
                  <span className="dv-task-actions">
                    {dismissed ? (
                      <button className="dv-task-btn" title="Restore to the list" onClick={e => { e.stopPropagation(); restoreTask(t); }}>↩</button>
                    ) : done ? (
                      <>
                        <button className="dv-task-btn" title="Mark open" onClick={e => { e.stopPropagation(); toggleDone(t); }}>↺</button>
                        <button className="dv-task-btn dv-task-btn--confirm" title="Confirm done — remove from this report" onClick={e => { e.stopPropagation(); confirmRemove(t); }}>Accept</button>
                      </>
                    ) : deleted ? (
                      <>
                        <button className="dv-task-btn" title="Restore task" onClick={e => { e.stopPropagation(); toggleDeleted(t); }}>↩</button>
                        <button className="dv-task-btn dv-task-btn--confirmdel" title="Confirm delete — remove from this report" onClick={e => { e.stopPropagation(); confirmRemove(t); }}>Delete</button>
                      </>
                    ) : (
                      <>
                        <button className="dv-task-btn" title="Mark resolved" onClick={e => { e.stopPropagation(); toggleDone(t); }}>✓</button>
                        <button className="dv-task-btn dv-task-btn--del" title="Delete task" onClick={e => { e.stopPropagation(); toggleDeleted(t); }}>✕</button>
                      </>
                    )}
                  </span>
                )}
                {dismissed
                  ? <span className="dv-task-from">removed from report</span>
                  : done
                  ? <span className="dv-task-from">resolved — Accept to remove now</span>
                  : deleted
                  ? <span className="dv-task-from">deleted — Delete to remove now, else drops next week</span>
                  : (moved || t.created) && <span className="dv-task-from">{t.created ? 'added here' : `moved from ${t.basePerson}`}</span>}
              </div>
            );
          })}
          {colTasks.length === 0 && addingIn !== owner && <div className="dv-col-empty">{isTeam ? 'unassigned tasks land here' : 'drop tasks here'}</div>}
        </div>
      </div>
    );
  }

  if (isNotConfigured(error)) return <EmptyState view="To-Do" />;
  if (error) return <div className="dv-error">{error}</div>;
  if (!data) return <div className="dv-loading">Loading to-dos…</div>;

  return (
    <div className="dv-root">
      <div className="dv-toolbar">
        <span className="dv-title">Action items</span>
        <div className="dv-weeknav">
          <button className="dv-weekbtn" disabled={week === activeWeek} title="Previous week"
            onClick={() => setViewWeek(shiftWeek(week, -7))}>◀</button>
          <span className="dv-weeklabel">week of {weekIso(week)}</span>
          <button className="dv-weekbtn" disabled={isFuture} title="Next week"
            onClick={() => setViewWeek(shiftWeek(week, 7))}>▶</button>
        </div>
        {week === activeWeek && <button className="dv-chip" onClick={() => selectFile(data.source)}>open file</button>}
        <button className={`dv-chip ${hideClosed ? 'dv-chip--on' : ''}`} onClick={() => setHideClosed(v => !v)}>
          {hideClosed ? 'show done/deleted' : 'hide done/deleted'}
        </button>
        {removedCount > 0 && (
          <button className={`dv-chip ${showRemoved ? 'dv-chip--on' : ''}`} onClick={() => setShowRemoved(v => !v)}>
            {showRemoved ? 'hide removed' : `show removed (${removedCount})`}
          </button>
        )}
        {pending > 0 && (
          <span className="dv-pending" title="Dashboard edits (reassign / resolve / delete / create) not yet folded into the source markdown — the /mot-sync propagation step applies them">
            {pending} pending sync
          </span>
        )}
        <GeneratedStamp data={data} onReload={reload} />
      </div>

      {isFuture && (
        <div className="dv-projnote">
          Projected report — carry-over of open tasks. Tasks resolved or deleted in the current week (and shown green there) drop off here; nothing is removed until <code>/mot-sync</code> publishes and rolls the week forward.
        </div>
      )}

      {/* Team column is a fixed sidebar OUTSIDE the scroller; members scroll in
          their own region to its right, so nothing ever passes under it. */}
      <div className="dv-board">
        {renderColumn(team)}
        <div className="dv-board-scroll">
          {columns.filter(o => o !== team).map(renderColumn)}
        </div>
      </div>

      <div className="dv-section">
        <h2 className="dv-h2">External / pending responses ({data.external_pending.length})</h2>
        <ul className="dv-bullets dv-bullets--two-col">
          {data.external_pending.map((e, i) => (
            <li key={i}><strong>{e.party}:</strong> {e.expected}</li>
          ))}
        </ul>
      </div>

      <div className="dv-section">
        <h2 className="dv-h2">Key dates</h2>
        <table className="dv-table dv-table--full">
          <tbody>
            {data.key_dates.map((k, i) => {
              const d = k.date_iso ? -daysSince(k.date_iso) : null; // days until
              return (
                <tr key={i}>
                  <td className="dv-date">{k.date_raw}</td>
                  <td>{k.event}</td>
                  <td className="dv-date">
                    {d == null ? '' : d < 0 ? `${-d}d ago` : d === 0 ? 'today' : `in ${d}d`}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Calendar — events agenda, grouped by month
//
// Read-only projection of __Operations/Documentation/Events.md (→ events.json,
// regenerated by mot-tools.js extract). Events are sparse (~a dozen across many
// months), so an agenda grouped by month reads better than a grid: upcoming is
// listed first with the next event flagged + a countdown; past is dimmed behind
// a toggle. The participation gate (Sync_Content_Schema §H) keeps unconfirmed
// event advertisements out of this feed entirely — only confirmed events appear.
// ---------------------------------------------------------------------------

const CAL_MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];
const CAL_WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

// Parse "YYYY-MM-DD" to a local-midnight Date (stable day math, no TZ drift).
function calParseDate(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return new Date(y, m - 1, d);
}

// "today" / "tomorrow" / "in 5d" / "yesterday" / "3d ago" from an ISO date.
function calRelative(iso) {
  const since = daysSince(iso);            // days since (negative = future)
  if (since == null) return '';
  const until = -since;
  if (until === 0) return 'today';
  if (until === 1) return 'tomorrow';
  if (until === -1) return 'yesterday';
  return until > 0 ? `in ${until}d` : `${-until}d ago`;
}

// Group an already-sorted event list into [{key, label, events:[]}] by month.
function calGroupByMonth(events) {
  const groups = [];
  for (const e of events) {
    const key = e.date.slice(0, 7);
    let g = groups[groups.length - 1];
    if (!g || g.key !== key) {
      g = { key, label: `${CAL_MONTHS[+key.slice(5) - 1]} ${key.slice(0, 4)}`, events: [] };
      groups.push(g);
    }
    g.events.push(e);
  }
  return groups;
}

function CalEventRow({ e }) {
  const undated = !e.date;
  return (
    <div className={`cal-event ${e.isPast ? 'cal-event--past' : ''} ${e.isNext ? 'cal-event--next' : ''} ${e.isToday ? 'cal-event--today' : ''} ${undated ? 'cal-event--undated' : ''}`}>
      <div className="cal-datechip" title={undated ? (e.date_raw || 'no date yet') : e.date}>
        {undated
          ? <span className="cal-day cal-day--tbd">TBD</span>
          : (<>
              <span className="cal-dow">{CAL_WEEKDAYS[e.dt.getDay()]}</span>
              <span className="cal-day">{e.dt.getDate()}</span>
            </>)}
      </div>
      <div className="cal-event-body">
        <span className="cal-event-text">{e.event}</span>
        {e.isNext && <span className="cal-nextflag">next</span>}
      </div>
      <span className="cal-rel">{calRelative(e.date)}</span>
    </div>
  );
}

function CalMonthGroups({ groups }) {
  return groups.map(g => (
    <div key={g.key} className="cal-month">
      <h3 className="cal-month-head">{g.label}</h3>
      <div className="cal-month-body">
        {g.events.map((e, i) => <CalEventRow key={e.date + i} e={e} />)}
      </div>
    </div>
  ));
}

export function CalendarView() {
  const { selectFile } = useDashboard();
  const [data, error, reload] = useData('events');
  const [showPast, setShowPast] = usePersistentState('cal-show-past', false);

  const { upcoming, past, undated, todayLabel } = useMemo(() => {
    if (!data?.events) return { upcoming: [], past: [], undated: [], todayLabel: '' };
    const today = new Date(); today.setHours(0, 0, 0, 0);
    const dated = data.events
      .filter(e => e.date && /^\d{4}-\d{2}-\d{2}$/.test(e.date))
      .map(e => {
        const dt = calParseDate(e.date);
        return { ...e, dt, isPast: dt < today, isToday: dt.getTime() === today.getTime() };
      })
      .sort((a, b) => a.dt - b.dt);
    const up = dated.filter(e => !e.isPast);
    if (up.length) up[0] = { ...up[0], isNext: true };        // first upcoming = "next"
    const pastDesc = dated.filter(e => e.isPast).reverse();   // most-recent past first
    const undatedEvents = data.events.filter(e => !e.date);   // confirmed but no date yet
    const tl = `${CAL_WEEKDAYS[today.getDay()]} ${today.getDate()} ${CAL_MONTHS[today.getMonth()].slice(0, 3)} ${today.getFullYear()}`;
    return { upcoming: calGroupByMonth(up), past: calGroupByMonth(pastDesc), undated: undatedEvents, todayLabel: tl };
  }, [data]);

  if (isNotConfigured(error)) return <EmptyState view="Calendar" />;
  if (error) return <div className="dv-error">{error}</div>;
  if (!data) return <div className="dv-loading">Loading calendar…</div>;

  const upCount = upcoming.reduce((n, g) => n + g.events.length, 0);
  const pastCount = past.reduce((n, g) => n + g.events.length, 0);

  return (
    <div className="dv-root">
      <div className="dv-toolbar">
        <span className="dv-title">Calendar</span>
        <span className="dv-count">{upCount} upcoming</span>
        {undated.length > 0 && <span className="dv-count">· {undated.length} undated</span>}
        {pastCount > 0 && (
          <button className={`dv-chip ${showPast ? 'dv-chip--on' : ''}`} onClick={() => setShowPast(v => !v)}>
            {showPast ? 'hide past' : `show past (${pastCount})`}
          </button>
        )}
        {data.source && <button className="dv-chip" onClick={() => selectFile(data.source)}>open Events.md</button>}
        <GeneratedStamp data={data} onReload={reload} />
      </div>

      <div className="cal-today">Today · {todayLabel}</div>

      {upCount === 0 && undated.length === 0
        ? <div className="dv-empty">No upcoming events.</div>
        : <CalMonthGroups groups={upcoming} />}

      {undated.length > 0 && (
        <div className="cal-month">
          <h3 className="cal-month-head cal-month-head--undated">No date yet</h3>
          <div className="cal-month-body">
            {undated.map((e, i) => <CalEventRow key={'u' + i} e={e} />)}
          </div>
        </div>
      )}

      {showPast && pastCount > 0 && (
        <>
          <div className="cal-divider">Past</div>
          <CalMonthGroups groups={past} />
        </>
      )}
    </div>
  );
}
